name: dbt_smoke
version: 1.0.0
config-version: 2
profile: dbt_smoke
model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

models:
  dbt_smoke:
    +materialized: table

seeds:
  dbt_smoke:
    +quote_columns: false
