import { Badge, EmptyState, InlinePath, PageHeader, SurfaceCard } from "@/components/ui";
import { loadAiMetrics } from "@/lib/data/artifacts";
import { decisionTone, formatNumber, formatPercent, severityTone } from "@/lib/utils";

export default async function AiPage() {
  const aiMetrics = await loadAiMetrics();

  if (!aiMetrics) {
    return (
      <EmptyState
        description="AI extension metrics are not available yet for this repository state."
        expectedFile="enforcer_report/ai_metrics.json"
        title="No AI artifact found"
      />
    );
  }

  const checks = Object.entries((aiMetrics.checks as Record<string, Record<string, unknown>> | undefined) ?? {});

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="AI contract extensions"
        title="AI-specific stability signals"
        description={
          <p>
            This view shows the AI-specific checks generated by the Week 7 pipeline, including embedding
            drift, prompt input stability, output schema stability, and trace contract integrity.
          </p>
        }
        aside={
          <SurfaceCard>
            <div className="space-y-3">
              <Badge tone={decisionTone(String(aiMetrics.overall_status ?? ""))}>
                {String(aiMetrics.overall_status ?? "Unknown")}
              </Badge>
              <p className="text-sm leading-7 text-[var(--muted)]">
                Registered trace consumers:{" "}
                {formatNumber(
                  Number(
                    (aiMetrics.summary as Record<string, unknown> | undefined)
                      ?.registered_trace_consumers ?? 0,
                  ),
                )}
              </p>
            </div>
          </SurfaceCard>
        }
      />

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <SurfaceCard>
          <p className="text-xs uppercase tracking-[0.2em] text-[var(--muted)]">Embedding drift</p>
          <p className="mt-3 font-display text-2xl text-[var(--ink)]">
            {formatNumber(
              Number(
                ((aiMetrics.checks as Record<string, Record<string, unknown>>).embedding_drift
                  ?.value as number | undefined) ?? 0,
              ),
            )}
          </p>
        </SurfaceCard>
        <SurfaceCard>
          <p className="text-xs uppercase tracking-[0.2em] text-[var(--muted)]">Prompt input violations</p>
          <p className="mt-3 font-display text-2xl text-[var(--ink)]">
            {formatPercent(
              Number(
                ((aiMetrics.checks as Record<string, Record<string, unknown>>)
                  .prompt_input_schema_validation?.value as number | undefined) ?? 0,
              ) * 100,
              2,
            )}
          </p>
        </SurfaceCard>
        <SurfaceCard>
          <p className="text-xs uppercase tracking-[0.2em] text-[var(--muted)]">Output schema violations</p>
          <p className="mt-3 font-display text-2xl text-[var(--ink)]">
            {formatPercent(
              Number(
                ((aiMetrics.checks as Record<string, Record<string, unknown>>)
                  .llm_output_schema_validation?.value as number | undefined) ?? 0,
              ) * 100,
              2,
            )}
          </p>
        </SurfaceCard>
        <SurfaceCard>
          <p className="text-xs uppercase tracking-[0.2em] text-[var(--muted)]">Trace contract rate</p>
          <p className="mt-3 font-display text-2xl text-[var(--ink)]">
            {formatPercent(
              Number(
                ((aiMetrics.checks as Record<string, Record<string, unknown>>).trace_contract_risk
                  ?.value as number | undefined) ?? 0,
              ) * 100,
              2,
            )}
          </p>
        </SurfaceCard>
      </div>

      <div className="columns-1 gap-6 xl:columns-2 [column-gap:1.5rem]">
        {checks.map(([key, check]) => (
          <SurfaceCard className="mb-6 break-inside-avoid" key={key}>
            <div className="flex flex-wrap items-center gap-2">
              <Badge tone={severityTone(String(check.status ?? ""))}>
                {String(check.status ?? "Unknown")}
              </Badge>
              <Badge tone={severityTone(String(check.severity ?? ""))}>
                {String(check.severity ?? "Unknown")}
              </Badge>
            </div>
            <h2 className="mt-4 font-display text-2xl text-[var(--ink)]">{key}</h2>
            <p className="mt-3 text-sm leading-7 text-[var(--muted)]">
              {String(check.summary ?? "No summary recorded for this metric.")}
            </p>

            {"metric_source" in check ||
            ("provider" in check && check.provider) ||
            ("model" in check && check.model) ||
            "thresholds" in check ? (
              <div className="mt-5 grid gap-3 sm:grid-cols-2">
                {"metric_source" in check ? (
                  <div className="rounded-xl border border-[var(--line)] bg-white/72 px-4 py-3">
                    <p className="text-[11px] uppercase tracking-[0.18em] text-[var(--muted)]">
                      Metric source
                    </p>
                    <p className="mt-2 text-sm font-semibold text-[var(--ink)]">
                      {String(check.metric_source ?? "Unknown")}
                    </p>
                  </div>
                ) : null}
                {"provider" in check && check.provider ? (
                  <div className="rounded-xl border border-[var(--line)] bg-white/72 px-4 py-3">
                    <p className="text-[11px] uppercase tracking-[0.18em] text-[var(--muted)]">Provider</p>
                    <div className="mt-2">
                      <InlinePath>{String(check.provider)}</InlinePath>
                    </div>
                  </div>
                ) : null}
                {"model" in check && check.model ? (
                  <div className="rounded-xl border border-[var(--line)] bg-white/72 px-4 py-3">
                    <p className="text-[11px] uppercase tracking-[0.18em] text-[var(--muted)]">Model</p>
                    <p className="mt-2 text-sm font-semibold text-[var(--ink)]">{String(check.model)}</p>
                  </div>
                ) : null}
                {"thresholds" in check ? (
                  <div className="rounded-xl border border-[var(--line)] bg-white/72 px-4 py-3">
                    <p className="text-[11px] uppercase tracking-[0.18em] text-[var(--muted)]">
                      Thresholds
                    </p>
                    <p className="mt-2 text-sm leading-6 text-[var(--muted)]">
                      {JSON.stringify(check.thresholds)}
                    </p>
                  </div>
                ) : null}
              </div>
            ) : null}

            {"notes" in check && Array.isArray(check.notes) && check.notes.length ? (
              <div className="mt-5 rounded-xl border border-[var(--line)] bg-[var(--paper)]/82 px-4 py-4">
                <p className="text-[11px] uppercase tracking-[0.18em] text-[var(--muted)]">Interpretation</p>
                <ul className="mt-3 space-y-2 text-sm leading-7 text-[var(--muted)]">
                  {(check.notes as string[]).map((note) => (
                    <li key={note}>- {note}</li>
                  ))}
                </ul>
              </div>
            ) : null}
          </SurfaceCard>
        ))}
      </div>
    </div>
  );
}
